Etimo/diamonds2

- package.json
- src/controllers/boards/boards.controller.ts
- src/gameengine/board.ts
- src/models/operation-queue.event.ts
- src/services/board.service.ts
- src/services/bots.service.ts
- yarn.lock
Handle queueing of simultaneous requests to a single board. Currently implemented for both join and move.
Closes #16
> Operation queue

- src/gameengine/board.ts
- src/gameengine/gameobjects/abstract-game-object.ts
- src/gameengine/gameobjects/teleport/teleport.spec.ts
- src/gameengine/gameobjects/teleport/teleport.ts
> 10 teleport game object

- src/gameengine/board.spec.ts
- src/gameengine/board.ts
> Handle outOfBounds #9

- backend/src/gameengine/board.ts
- backend/src/services/board.service.ts
> Rate limit bot moves

- backend/src/controllers/boards/boards.controller.ts
- backend/src/gameengine/board.ts
- backend/src/main.ts
- backend/src/models/board.dto.ts
- backend/src/services/board.service.ts
- backend/src/services/bots.service.ts
> Fix board id type

- backend/src/gameengine/board.spec.ts
- backend/src/gameengine/board.ts
A lot of the crucial functionality is in the board. It is important to have some test covering that as well
> Add more tests

- backend/src/gameengine/gameobjects/dummy-bot/dummy-bot-provider.spec.ts
- backend/src/gameengine/gameobjects/dummy-bot/dummy-bot-provider.ts
- backend/src/gameengine/gameobjects/dummy-bot/dummy-bot.ts
Ability to configure number of dummy bots.
> Make dummy bots configurable

- backend/package.json
- backend/src/app.module.ts
- backend/src/main.ts
- backend/src/services/board.service.spec.ts
- backend/src/services/board.service.ts
- backend/src/services/metrics.service.ts
- backend/yarn.lock
Add prometheus metrics to api.
Closes #17
> Prometheus metrics

- .github/workflows/main.yml
- docker-compose.prod-build.yml
- docker-compose.prod-run.yml
- docker-compose.yml
- example-bots/python/Dockerfile
- example-bots/python/game/bot.py
- example-bots/python/main.py
- example-bots/python/run-etimo-bots.sh
Two example bots are started in docker compose. Closes #82
> Etimo bots

- example-bots/python/game/logic/first_diamond.py
Our Etimo bots usually get stuck trying to go past each other... Looks a little silly and doesnt really give a nice first impression for new users in my opinion. Although not that important, still a small change that will make the bots turn if they are stuck for a move.
> Make example bot a little bit smarter

- backend/src/services/board.service.spec.ts
- backend/src/services/board.service.ts
Check each board when bot joins. Closes #96
> Only allow bot on one board at a time

- backend/src/gameengine/gameobjects/bot/bot.spec.ts
- backend/src/gameengine/gameobjects/bot/bot.ts
- example-bots/python/.gitignore
Should it always be possible to tackle? Right now the other bot is pushed to its base when tackled. The tackling bot also steals diamonds from the victim.
Closes #74
> Tackle bots

- backend/src/services/board.service.spec.ts
- backend/src/services/board.service.ts
- backend/src/services/metrics.service.ts
Added boards_total to metrics.
Closes #124
> Added metrics for number of boards.

- .github/workflows/main.yml
Executing "docker system prune -af" during deploy to free up space.
Closes #91
> Added docker system prune during deploy to prod.

- backend/src/gameengine/README.md
- backend/src/gameengine/board.spec.ts
- backend/src/gameengine/gameobjects/bot/bot-provider.spec.ts
- backend/src/gameengine/gameobjects/bot/bot-provider.ts
- backend/src/gameengine/gameobjects/bot/bot.spec.ts
- backend/src/gameengine/gameobjects/bot/bot.ts
- backend/src/gameengine/gameobjects/dummy-bot/dummy-bot-provider.spec.ts
- backend/src/gameengine/gameobjects/dummy-bot/dummy-bot-provider.ts
- backend/src/services/board.service.ts
Added canTackle to BotProvider.
We can now set if a bot should be able to tackle other bots.
Closing #108
> Added canTackle to BotProvider.

- backend/src/app.module.ts
- backend/src/controllers/slack/slack.controller.ts
Added POST /api/slack/seasons endpoint to try slack slash commands
> Added slack endpoint to test integration.

- backend/src/gameengine/board.ts
- backend/src/services/board.service.ts
Removing bot from board after 10 rate limit violations to /move endpoint
closes #67
> Removing bot after 10 rateLimitViolations.

- backend/src/services/teams.service.spec.ts
- backend/src/services/teams.service.ts
Added url validator to teams.
Closes #117
> Added url validator.

- backend/src/app.module.ts
- backend/src/middlewares/auto-scale-boards.middleware.spec.ts
- backend/src/middlewares/auto-scale-boards.middleware.ts
- backend/src/models/board-config.dto.ts
- backend/src/services/board-config.service.spec.ts
- backend/src/services/board-config.service.ts
- backend/src/services/board.service.spec.ts
- backend/src/services/board.service.ts
We will now use the board_config from DB when creating the boards.
> Use board config

- backend/src/app.module.ts
- backend/src/db/models/boardConfig.entity.ts
- backend/src/middlewares/auto-scale-boards.middleware.spec.ts
- backend/src/middlewares/auto-scale-boards.middleware.ts
- backend/src/migration/1639053577477-add-board-config.ts
- backend/src/migration/1639053743945-add-off-season-board-config.ts
- backend/src/models/board-config.dto.ts
- backend/src/services/board-config.service.spec.ts
- backend/src/services/board-config.service.ts
- backend/src/services/board.service.ts
> Added BoardConfig entity and migrations.

- frontend/package.json
- frontend/src/App.js
- frontend/src/index.js
fixes #207 
Swapped `<Switch />` to `<Routes />` due to deprecation. [Source](https://reactrouter.com/docs/en/v6/upgrading/v5#upgrade-to-react-router-v6)
> Updated all front-end dependencies to the most recent version

- frontend/src/blocks/Header/Button.js
- frontend/src/blocks/Header/index.js
- frontend/src/blocks/RegisterBot/Button.js
- frontend/src/blocks/RegisterBot/Close.js
- frontend/src/blocks/RegisterBot/Error.js
- frontend/src/blocks/RegisterBot/Form.js
- frontend/src/blocks/RegisterBot/Input.js
- frontend/src/blocks/RegisterBot/Label.js
- frontend/src/blocks/RegisterBot/Response.js
- frontend/src/blocks/RegisterBot/ResponseWrapper.js
- frontend/src/blocks/RegisterBot/Title.js
- frontend/src/blocks/RegisterBot/index.js
- frontend/src/components/Header.js
- frontend/src/components/RegisterBotModal.js
- frontend/src/hooks/index.js
- frontend/src/hooks/usePost.js
- frontend/src/pages/game.js
> feat: Added form modal to register bot

- frontend-typescript/src/App.tsx
- frontend-typescript/src/components/Grid.tsx
- frontend-typescript/src/components/Header.tsx
- frontend-typescript/src/components/SideMenu.tsx
- frontend-typescript/src/components/Spacer.tsx
- frontend-typescript/src/components/index.ts
Added basic components to get development of new frontend started.
> TypeScript - Added basic compontens

- backend/prisma/migrations/20230420194431_add_dummy_bots_flag_to_boardconfig/migration.sql
- backend/prisma/schema.prisma
- backend/prisma/seed.ts
- backend/src/gameengine/board.ts
- backend/src/gameengine/gameobjects/base/base.ts
- backend/src/gameengine/gameobjects/dummy-bot/dummy-bot.ts
- backend/src/services/board.service.ts
- backend/src/types/board-config.ts
> feat: add dummy bot provider #294

- packages/frontend/src/components/Board/Board.tsx
- packages/frontend/src/components/Board/Cell.tsx
- packages/frontend/src/components/Modal.tsx
- packages/frontend/src/components/PlayerTable.tsx
- packages/frontend/src/components/Rules.tsx
- packages/frontend/src/index.css
- modal closes on click
- new board cell color in light mode
- fix breaking cell aspect ratio in different viewports
- use diamond image in PlayerTable
> style: fix consistent cell aspect ratio, add close modal on click, update cell border color

- packages/frontend/src/components/Board/Cell.tsx
- packages/frontend/src/components/HighScoreTable.tsx
- packages/frontend/src/components/SideMenu/SideMenu.tsx
using a valid UUID('00000000-0000-0000-0000-000000000000') when setting the initial seasonId instead of '0' in the frontend appears to solve the issue.
> fix: 319 bug error when adding new highscore for dummy bots

- README.md
- package.json
- scripts/setup-db-prisma.sh
This should add some minor fixes to the local development setup, mainly to automate the seeding and update the documentation with correct instructions.
A bash script to automate the creation and seeding of the database is added with a corresponding npm script.
> Minor fixes to the development setup

- packages/backend/src/gameengine/gameobjects/bot/bot-provider.spec.ts
- packages/backend/src/gameengine/gameobjects/bot/bot.spec.ts
- packages/backend/src/gameengine/gameobjects/bot/bot.ts
The bots don't need the board, they only interact with each other.
Update all the tests for bots to work.
> refactor: bot methods don't use board

- packages/backend/src/gameengine/board.ts
- packages/backend/src/gameengine/gameobjects/abstract-game-object.ts
- packages/backend/src/gameengine/gameobjects/base/base.spec.ts
- packages/backend/src/gameengine/gameobjects/bot/bot-provider.ts
- packages/backend/src/gameengine/gameobjects/bot/bot.spec.ts
- packages/backend/src/gameengine/gameobjects/bot/bot.ts
- packages/backend/src/gameengine/gameobjects/diamond/diamond.ts
- packages/backend/src/gameengine/gameobjects/dummy-bot/dummy-bot.ts
- packages/backend/src/gameengine/gameobjects/teleport/teleport.ts
- packages/backend/src/gameengine/operation-queue-board.ts
- packages/backend/src/services/board.service.ts
- packages/backend/src/types/position.ts
Replace the interface with a type from our shared lib. This will make it easier to reuse the type for both the frontend and backend.
> refactor: replace IPosition with Position

- packages/backend/src/gameengine/board.spec.ts
- packages/backend/src/gameengine/gameobjects/base/base-provider.spec.ts
All tests should now have correct syntax and run correctly.
Not all tests pass, this is expected.
> test: fix board tests
